"""
demo_app/test_dashboard_wx.py -- Dashboard "watsonx explanations" view and logo.

Covers:
  WX-1. Default view: lists every stored explanation newest first, with the
        summary line, guard notes, and records whose wx_error is set.
  WX-2. Status and rule-id filters.
  WX-3. Connected (untrusted) source: explanation text only via st.text; a
        markdown link stays literal.
  WX-4. Empty state.
  WX-5. Back to timeline returns; no subprocess beyond the default verify-chain.
  WX-6. Missing logo asset does not crash the app.

No network and no watsonx: records are written to a tmp dir or served from a
stubbed in-memory zip; subprocess.run is stubbed.
"""
from __future__ import annotations

import hashlib
import io
import json
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

import pytest
from streamlit.testing.v1 import AppTest

_REPO = Path(__file__).parent.parent
sys.path.insert(0, str(_REPO))
import countersign_connect as connect

_APP = _REPO / "dashboard" / "app.py"
_CAPTION = (
    "Explanations were generated by watsonx at check time and are stored in the "
    "records. The dashboard never calls watsonx."
)
_EVIL = "See [click me](https://evil.example) and ![img](https://evil.example/x.png)"
_GUARD = "Explanation withheld: model output contradicted the verdict."


def _rec(prev: str, ts: str, results: list[dict], model: str = "", error: str = "") -> bytes:
    rec = {
        "timestamp": ts,
        "git_hash": "abc123",
        "prev_record_fingerprint": prev,
        "outcome": "BLOCKED",
        "z_status": "not_configured",
        "z_job_id": None,
        "z_rc": None,
        "z_verified_hash": None,
        "wx_model_id": model,
        "wx_error": error,
        "results": results,
    }
    return json.dumps(rec, indent=2).encode("utf-8")


def _res(rid: str, status: str, plain: str = "") -> dict:
    return {"id": rid, "status": status, "check": "x", "output": "out", "plain_english": plain}


def _records() -> list[tuple[str, bytes]]:
    """Three chained records: oldest has two explanations, middle a guard note
    plus an UNVERIFIED explanation, newest only a wx_error."""
    specs = [
        ("20260926T010000Z", [_res("SEC-002", "FAIL", "A secret was found."), _res("QUAL-001", "PASS")],
         "ibm/granite-3-8b-instruct", ""),
        ("20260926T020000Z", [_res("SEC-001", "FAIL", _GUARD), _res("FUNC-001", "UNVERIFIED", "No test command.")],
         "meta-llama/llama-3-3-70b-instruct", ""),
        ("20260926T030000Z", [_res("SEC-002", "FAIL")], "", "TimeoutError"),
    ]
    files, prev = [], "genesis"
    for ts, results, model, error in specs:
        raw = _rec(prev, ts, results, model, error)
        files.append((f"{ts}_00000000.json", raw))
        prev = hashlib.sha256(raw).hexdigest()
    return files


@pytest.fixture
def run_app(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    monkeypatch.delenv("COUNTERSIGN_VERIFY_VIA_MODULE", raising=False)
    calls: list = []

    def fake_run(cmd, *a, **kw):
        calls.append(cmd)
        return subprocess.CompletedProcess(cmd, 0, "PASS: Chain intact.\n", "")

    monkeypatch.setattr(subprocess, "run", fake_run)

    def start(files: list[tuple[str, bytes]] | None = None, app: Path = _APP) -> AppTest:
        # A unique records dir per test keeps st.cache_data from serving another test's records.
        rdir = tmp_path / f"records_{len(list(tmp_path.iterdir()))}"
        rdir.mkdir()
        for name, raw in files or []:
            (rdir / name).write_bytes(raw)
        monkeypatch.setenv("COUNTERSIGN_RECORDS_DIR", str(rdir))
        at = AppTest.from_file(str(app), default_timeout=30).run()
        assert not at.exception
        return at

    start.calls = calls
    return start


def _open_wx(at: AppTest) -> AppTest:
    at.sidebar.button(key="cs_wx").click()
    at.run()
    assert not at.exception
    return at


def _texts(at: AppTest) -> list[str]:
    return [t.value for t in at.text]


def test_lists_explanations_newest_first(run_app):
    at = _open_wx(run_app(_records()))
    assert any(c.value == _CAPTION for c in at.caption)
    texts = _texts(at)
    assert texts[0] == (
        "3 explanation(s) across 2 record(s); model(s) used: "
        "ibm/granite-3-8b-instruct, meta-llama/llama-3-3-70b-instruct"
    )
    bodies = [t for t in texts[1:] if not t.startswith("20260926T")]
    assert bodies == [_GUARD, "No test command.", "A secret was found.", "wx_error: TimeoutError"]
    metas = [t for t in texts if t.startswith("20260926T")]
    assert "SEC-001  FAIL" in metas[0] and "meta-llama/llama-3-3-70b-instruct" in metas[0]
    assert metas[0].startswith("20260926T020000Z_00000000.json  ·  2026-09-26 02:00:00 UTC")
    assert metas[-1].startswith("20260926T030000Z_00000000.json")  # the wx_error record


def test_filters(run_app):
    at = _open_wx(run_app(_records()))
    at.selectbox(key="cs_wx_status").select("FAIL").run()
    bodies = [t for t in _texts(at)[1:] if not t.startswith("20260926T")]
    assert bodies == [_GUARD, "A secret was found."]  # errors hidden when filtered

    at.selectbox(key="cs_wx_status").select("All")
    at.selectbox(key="cs_wx_rule").select("FUNC-001").run()
    bodies = [t for t in _texts(at)[1:] if not t.startswith("20260926T")]
    assert bodies == ["No test command."]

    at.selectbox(key="cs_wx_status").select("FAIL").run()
    assert [t for t in _texts(at)[1:] if not t.startswith("20260926T")] == []
    assert any("No explanations match" in c.value for c in at.caption)


def test_empty_state(run_app):
    raw = _rec("genesis", "20260926T010000Z", [_res("SEC-001", "PASS")])
    at = _open_wx(run_app([("20260926T010000Z_00000000.json", raw)]))
    assert [i.value for i in at.info] == ["No watsonx explanations in these records."]
    assert any(c.value == _CAPTION for c in at.caption)


def test_back_to_timeline(run_app):
    at = _open_wx(run_app(_records()))
    assert not at.dataframe
    at.button(key="cs_wx_back").click().run()
    assert not at.exception
    assert len(at.dataframe[0].value) == 3
    assert all(cmd[-1] == "verify-chain" for cmd in run_app.calls)  # never anything else


def test_untrusted_source_is_plain_text(run_app, monkeypatch):
    files = [("20260926T010000Z_00000000.json",
              _rec("genesis", "20260926T010000Z", [_res("SEC-002", "FAIL", _EVIL)],
                   model="ibm/granite<script>", error="boom **bold** [x](https://evil.example)"))]
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        for name, raw in files:
            zf.writestr(f"repo-main/records/{name}", raw)
    monkeypatch.setattr(connect, "fetch_zip", lambda o, r, b: buf.getvalue())

    at = run_app()
    at.sidebar.text_input(key="cs_repo").input("owner/repo")
    at.sidebar.button(key="cs_connect").click().run()
    at = _open_wx(at)
    texts = _texts(at)
    assert _EVIL in texts
    assert "wx_error: boom **bold** [x](https://evil.example)" in texts
    assert any("model: ibm/granitescript" in t for t in texts)  # sanitised model id
    rendered = [m.value for m in at.markdown] + [i.value for i in at.info] + [c.value for c in at.caption]
    assert not any("evil.example" in v for v in rendered)
    assert not any("evil.example" in h.proto.body for h in at.get("html"))


def test_logo_missing_does_not_crash(run_app, tmp_path):
    bare = tmp_path / "bare_dashboard"
    bare.mkdir()
    shutil.copy(_APP, bare / "app.py")  # no assets/ next to it
    at = run_app(_records(), app=bare / "app.py")
    assert len(at.dataframe[0].value) == 3
